Eip 123 GitHub actions for FE
Guardos-Epitech/Guardos-dev pull request #1
Opened 2023-05-13 13:19 UTC by RenanDbs

Multiple commit are due to the obligation to push each time i want to test it

2023-05-15 16:30 UTC, Alban-de-tourtier commented on package-lock.json
Remove the package-lock.json

2023-05-15 17:59 UTC, JosefineM2000 requested changes

2023-05-15 17:59 UTC, JosefineM2000 commented on .github/workflows/ci_fe.yml
> +name: Node.js CI
Please rename to something with FE, for example "Frontend CI"

2023-05-16 13:12 UTC, RenanDbs commented on .github/workflows/ci_fe.yml
> +name: Node.js CI
Done and changed to Frontend VisitorWeb CI

2023-05-16 18:44 UTC, JosefineM2000 approved these changes
Pay attention to the merge conflict, otherwise LGTM

2023-05-17 07:54 UTC, merged